#############################
##     TOP Level PATH      ##
#############################
TO_ROOT =../..


############################
##     Include Paths      ##
############################
INCLUDES = $(3P_INCLUDES) $(COMMON_INCLUDES)

############################
##    Common Defines      ##
############################
include $(TO_ROOT)/MakeDefines


